### ISSUE TITLE
GalleryFolder is not creating by build proccess

### ISSUE THREAD

**Issue by Cheprer** [TripleEmcoder/Orchard#1]
I did, what was said here: http://www.caliper.pl/en/node/172 to manually build the Orchard project and create packages. I need it for an updated version of Orchard to use some of the added features. I had some problems with MS build and some nuget packages for ConsoleApplication1, which I had to go and run the project manually to download the nugets and then I got to the phase I can't solve so easily and I guess it should be fixed.

When I try to do "msbuild myLocationToOrchardFolder\Orchard\Orchard.proj" I'm getting this error:

"c:\Users\Hounslow\Documents\GitHub\Orchard\Orchard.proj" (default target) (1)
-> (Stage-Modules target)
-> c:\Users\Hounslow\Documents\GitHub\Orchard\Orchard.proj(48,3): error MSB6003:
 The specified task executable "cmd.exe" could not be run. The working directory "c:\Users\Hounslow\Documents\GitHub\Orchard\upstream\build\Gallery" does not
exist."

I've tried to create it but it is automatically deleting the upstream folder on the start of the execution of the command above. I understand why it is, it's alright but it should have create that folder by the code then but the issue is that it doesn't.

Any solution or can you fix this in your code in here please? Maybe some side question is possible just to put the zip folder of Orchard of newer version like 1.8.1 and then I'll get the packages of Orchard of that version?

Thanks, Cheprer

**Comment by TripleEmcoder** [comment]
We haven't pursued this idea any further since the original post, so the scripts haven't been updated for later Orchard versions, as you found out. I'm sorry I cannot help you at the moment, but if you find a solution please share it here!

**Comment by Cheprer** [comment]
Ok I solved this one by putting this line of code inside the file *\Orchard\Orchard.proj into the 
`<Target Name="Package"></Target>` element.:
`<MakeDir Directories="$(GalleryArtifactFolder);$(GalleryFolder)" />`

but I got this now 

Stage-Modules:
  "c:\Users\Hounslow\Documents\GitHub\Orchard\upstream\build\Gallery\bin\Orchard.exe" package create  "c:\Users\Hounslow\Documents\GitHub\Orchard\upstream\artifacts\Gallery"
The system cannot find the path specified.
c:\Users\Hounslow\Documents\GitHub\Orchard\Orchard.proj(49,3): error MSB3073: T
he command ""c:\Users\Hounslow\Documents\GitHub\Orchard\upstream\build\Gallery\
bin\Orchard.exe" package create  "c:\Users\Hounslow\Documents\GitHub\Orchard\up
stream\artifacts\Gallery"" exited with code 3.

So now it looks that the current files you have without any change won't work because they are not deploying into the Gallery folders, which I've checked that they are empty after this call. Any ideas why, I've tried to find it but it seems ok?
